---
title: 'Reproducible Research Peer Assignment #1'
author: "Shanna Ricketts"
date: "Saturday, June 13, 2015"
output: html_document
---

```{r}
echo = TRUE #always make code visible
```

```{r}
#Loading and preprocessing the data
x<-read.csv("activity.csv")
options(repos = c(CRAN = "http://cran.rstudio.com"))
install.packages("dplyr")
library("dplyr")
```

```{r}
#What is the mean total number of steps taken per day?

##Total number of steps taken per day
total_steps <- x%>%group_by(date)%>%summarise(sum(steps, na.rm = TRUE))

## Histogram of the total number of steps taken each day
hist(total_steps$sum)

##Mean of the total number of steps taken per day
mean_steps <- mean(total_steps$sum)
mean_steps

##Median of the total number of steps taken per day
median_steps <- median(total_steps$sum)
median_steps
```

```{r}
#What is the average daily activity pattern?
interval <- x%>%group_by(interval) %>% summarise(mean(steps, na.rm = TRUE))

## Time Series Plot
plot(interval$interval, interval$mean, type = "l")

##5-minute interval that contains the maximum number of steps
max_interval <- summarise(interval, max(interval$mean))
max_interval
```

```{r}
#Imputing missing values
##Total number of missing values in the dataset
sum(is.na(x))

##Fill in missing values in the dataset
m<-merge(x, interval, by = "interval")

for (i in 1:nrow(m)){
        if (is.na(m$steps[i])) {
              m$steps_new[i] <- m$mean[i]
      }
      else {
        m$steps_new[i]<-m$steps[i] 
      }
        }

##New dataset
head(m)

##Histogram of total number of steps taken each day
total_steps_new <- m%>%group_by(date)%>%summarise(sum(steps_new))
hist(total_steps_new$sum)

## Mean total number of steps taken per day
mean_steps_new <- mean(total_steps_new$sum)
mean_steps_new

## Median total number of steps taken per day
median_steps_new <- median(total_steps_new$sum)
median_steps_new

##Do these values differ from the first part of the assignment?
##What is the impact of imputing missing data on the estimates of the total daily number of step?
```

```{r}
#Are there differences in activity patterns between weekdays and weekends?
```
